name: Vaishaal Shankar
description: an infrequently authored blog
meta_description: ""

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15
baseurl: /blog/
domain_name: 'http://vaishaal.com'
google_analytics: 'UA-XXXXXXXX-X'

# Gems
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'vaishaal.com/blog'
author:         'Vaishaal Shankar'

